sudo: required
language: node_js
node_js:
  - 8.12.0
python:
  - "3.6"
env:
  - FLASK_APP=REST/server.py
before_install:
  - sudo apt-get -y install python3-pip python-dev
  - sudo pip3 install -U setuptools
install:
  - sudo pip3 install -r requirements.txt
  - cd frontend
  - npm install
  - npm install newman
  - npm run dev
before_script:
  - cd ..
  - set FLASK_APP=REST/server.py
  - nohup flask run >output &
  - sleep 5s
  - cd frontend
script:
  - node_modules/.bin/newman run tests/postman/4YP.postman_collection.json -e tests/postman/4YP.postman_environment.json --global-var postman_username=$postman_username --global-var postman_password=$postman_password -n 5 --delay-request 500
  - cd ..
  - cat output